name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        working-directory: packages/vital-devices-react-native
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: ci
        working-directory: packages/vital-devices-react-native
        run: npm ci
      - name: publish
        working-directory: packages/vital-devices-react-native
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
